### ISSUE TITLE
CUDA ERROR fs_initializer.cu.h: 141 invalid device symbol

### ISSUE THREAD

**Issue by fengyangyang98** [gpufs/gpufs#3]
Hi Sagi and Mark,
I am studying your project recently. I found this error all the time while compiling the samples: "CUDA ERROR fs_initializer.cu.h: 141 invalid device symbol". I looked at the source code and found that this is related to cudaMemcpyToSymbol, but it seems that the use of this function is correct. 
I compiled your project with cuda 9.0. Hoping to get your reply, I would be very grateful.

**Comment by fengyangyang98** [comment]
I fond the reason.
In my gpu, when compiling, the setting should be "-gencode arch=compute_70,code=sm_70".

**Comment by gpufs** [comment]
Hi,
Which branch did you use?
Mark

**Comment by fengyangyang98** [comment]
Hi,
I used the master branch.
